Update documentation

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -3,6 +3,11 @@
 
 echo '🕵️‍♂️ Checking your crappy code 🕵️‍♂️'
 
+echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ clean 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
+yarn clean || (echo '🤢🤮🤢 clean failed 🤢🤮🤢'; false)
+echo '✅✅✅ clean ✅✅✅'
+
+
 echo '🕵️‍♂️🕵️‍♂️🕵️‍♂️ deadCode:check 🕵️‍♂️🕵️‍♂️🕵️‍♂️'
 yarn deadCode:check || (echo '🤢🤮🤢 deadCode:check failed 🤢🤮🤢'; false)
 echo '✅✅✅ deadCode:check ✅✅✅'
